### ISSUE TITLE
 ( programming-1 ) variable names should be easier for beginner to understand...

### ISSUE THREAD

**Issue by ahsanali2009** [nragland37/cpp-projects#20]
The Programming-I folder is for complete beginners to practice open-source stuff... as a new person to programming myself I have noticed that the variable are a bit hard to understand for new developers. Variables can be re-labeled, they should be detailed and should have easy wording.

**Comment by nragland37** [comment]
> The Programming-I folder is for complete beginners to practice open-source stuff... as a new person to programming myself I have noticed that the variable are a bit hard to understand for new developers. Variables can be re-labeled, they should be detailed and should have easy wording.

Great idea! Would you like to contribute and PR?

**Comment by ahsanali2009** [comment]
@nragland37  Sure, I will start working soon!

**Comment by ahsanali2009** [comment]
Hey @nragland37 , I have worked on this issue and opened a PR, look at the changes and merge them.

**Comment by nragland37** [comment]
@ahsanali2009, Great! I will review your changes soon as I can. I'll only accept the updates I agree with ~ 

Appreciate your work, keep it up!
